language: python
script:
- python setup.py sdist
- export ARTIFACT_SDIST=`ls dist/*tar.gz`
- echo $ARTIFACT_SDIST
deploy:
  provider: releases
  api_key:
    secure: LQLLQ5p0inq9b4+26RByrgrklDNZu37CNMza2WXj5a9p3JDeBl6jpUkibiIBFdhLzhBfqUaiY0BO3YZNZWOvzuEJPql2maqfj82iQdFfkxpAmqZ19T14tmBdgR6QV2TLNXEuB4/d54b6VIaz4pys4o77+3EX30iuqssGDXY4okJJpxbODmd+j8R1x+B3OtIunoxTCkEM/A2JB0FSg6G0fDfZDq5P+5mIBdPA9DdfaUFdJl/+ZFmRJWREMUsSbX1cOolZmMj87uYRtW+aRTB/gPDwyz8PVS6jmG7JaW6gllCYFn0LyqWrinxEfv6tGaTbaPlrRhccrpRrPVbvWpJ/xHjl6hRewtpZt/BtBz3gZ+EiheMZ2Iz3jmOqsl1bzWwDMRwJB+g6GD6U7nvrmAmZ4amj2LT8dKWTqYiFTshSjdGZrLB4b0RVprzUpGWQZYBj2cvYW+TVElKLcRUNJPWjqu+9A85FOIHBTPo8s1vjcCa3cAbQJsvMqS2HvHUsmvBz3S/pMgbQYlncWYSPDcG3E7bysVD9AQvooHan2PK+1ggi4K8j16IbtrpzLGLR9zIY90Cc2cDUB7qLG4Dq1Rw4YMlJbg89anaKJ+hRe4n/GHUab6x92d2Xl8kxMN2MHymK7BWLhnHRL5LE6rrKAtaqtklJzF1GjakGxE9+IwH8mFY=
  skip_cleanup: true
  file: $ARTIFACT_SDIST
  on:
    repo: cpascual/PAScual
    tags: true
