language: python
script:
- python setup.py sdist
- export ARTIFACT_SDIST=`ls dist/*tar.gz`
- echo $ARTIFACT_SDIST
deploy:
  - provider: releases
    api_key:
      secure: LQLLQ5p0inq9b4+26RByrgrklDNZu37CNMza2WXj5a9p3JDeBl6jpUkibiIBFdhLzhBfqUaiY0BO3YZNZWOvzuEJPql2maqfj82iQdFfkxpAmqZ19T14tmBdgR6QV2TLNXEuB4/d54b6VIaz4pys4o77+3EX30iuqssGDXY4okJJpxbODmd+j8R1x+B3OtIunoxTCkEM/A2JB0FSg6G0fDfZDq5P+5mIBdPA9DdfaUFdJl/+ZFmRJWREMUsSbX1cOolZmMj87uYRtW+aRTB/gPDwyz8PVS6jmG7JaW6gllCYFn0LyqWrinxEfv6tGaTbaPlrRhccrpRrPVbvWpJ/xHjl6hRewtpZt/BtBz3gZ+EiheMZ2Iz3jmOqsl1bzWwDMRwJB+g6GD6U7nvrmAmZ4amj2LT8dKWTqYiFTshSjdGZrLB4b0RVprzUpGWQZYBj2cvYW+TVElKLcRUNJPWjqu+9A85FOIHBTPo8s1vjcCa3cAbQJsvMqS2HvHUsmvBz3S/pMgbQYlncWYSPDcG3E7bysVD9AQvooHan2PK+1ggi4K8j16IbtrpzLGLR9zIY90Cc2cDUB7qLG4Dq1Rw4YMlJbg89anaKJ+hRe4n/GHUab6x92d2Xl8kxMN2MHymK7BWLhnHRL5LE6rrKAtaqtklJzF1GjakGxE9+IwH8mFY=
    skip_cleanup: true
    file: $ARTIFACT_SDIST
    on:
      repo: cpascual/PAScual
      tags: true
  - provider: pypi
    user: cpascual_bot
    password:
      secure: "TJvMQIzkLseCaLR7oflxSx5ZQKZKG6H0DbBj28Gusq9TcXo9QvF5YOnt1LkFgLvPwLj9Ln7WCLPORWStbAjJcmceWvcXV8v/ujGJl8Vji85PJIaVAOPHBWWWlYeLWdhEEObI3nEUeexoTpnh6YkwxA7IMEezgl2r3x8UkmlR6M3nL1rZRvkUgavtYCPCwzmnkyJYuAV4LapnWX46vkc4D9KGc69DThE9eIvNWIjbvlkfwIvwY/1grkZls20kbXApzUJTMnrTbSmJcKh5p5yLPrlRq4Xp/kvRiLIUv5dUKorLqjW/VXi8NYKhfUQSUIKdaQIKdPkOvVB0KsRI8opARxb17Gk9z9I4R+KWDiSqqmJb5E6VhXg9hILSr4xSTb/EB5h90q2eOSFwwq+I5n0zIUK88abXeDsejCYw1VAGDHoKYqbFLDHcZBl6RDPsvEBYBZdFjUQ4UZQ2VsQZ9hb3XaPU5pAHWCpIJlaPI9F1Z52L38aliR5RdLFWmXUIziqGRZCGA+ccS3QR/3HOti2k1nNgEG3+nVP/La32sQyNKisMSr3w0RpRTXLfPE9LfG30GH3ZEETJWfWySchFBlJinwtkEw85ExC8IfDSpp2kNqEEIDLYVyMr3ci/Gjh/x4du7HDyYl7Bo2Lxz8hUMMn2mCz3t2vv0DcT1Wfl8aBHm68="
    on:
      repo: cpascual/PAScual
      tags: true