# fetch repository as zip archive
shallow_clone: true

environment:
    global:
        VENV_BUILD_DIR: "venv_build"

    matrix:
        # Python 2.7
        - PYTHON_DIR: "C:\\Python27-x64"

install:

    # Add Python to PATH
    - "SET PATH=%PYTHON_DIR%;%PYTHON_DIR%\\Scripts;%PATH%"

    # Upgrade/install distribution modules
    - "pip install --upgrade setuptools"
    - "python -m pip install --upgrade pip"

    # Install virtualenv
    - "pip install --upgrade virtualenv"
    - "virtualenv --version"

build_script:
    # Create build virtualenv
    - "virtualenv --clear %VENV_BUILD_DIR%"
    - "%VENV_BUILD_DIR%\\Scripts\\activate.bat"

    # Build
    - "python setup.py bdist_msi"
    - ps: "ls dist"

    # Leave build virtualenv
    - "%VENV_BUILD_DIR%\\Scripts\\deactivate.bat"
    - "rmdir %VENV_BUILD_DIR% /s /q"

artifacts:
    # Archive the generated wheel package in the ci.appveyor.com build report.
    - path: dist\*.msi
      name: PAScual_MSI

### See https://www.appveyor.com/docs/deployment/github/
deploy:
  #release: PAScual-v$(appveyor_build_version)
  description: 'PAScual Windows installer'
  provider: GitHub
  auth_token:
    secure: j5IxMH2IZxvrvoVMfRYiZYvWG4WA0qT5ucKl6ctgFtFmVGQ4/jGjPjsw4+2eCWtg
  artifact: PAScual_MSI
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
